### ISSUE TITLE
Normal users able to ban themselves (and potentially others?)

### ISSUE THREAD

**Issue by simondanerd** [Abb1x/Ububot#2]
Yes, I was dumb enough to ban myself, for purely testing sake only. I trust that this is being fixed, but I wanted to make an issue out of it anyways as a formality and to get the project into the Git workflow groove. 

An `if-then` statement should fix the problem most likely.

**Comment by Abb1x** [comment]
Thanks ! got fixed

**Comment by simondanerd** [comment]
Great! Thanks!
